### ISSUE TITLE
"Kóði og gögn" linkur virkar ekki inní https://metill.is/maelabord/sveitarfelog/"

### ISSUE THREAD

**Issue by arontommi** [bgautijonsson/Metill.is#1]
Kóði og gögn linkurinn reynir að opna github inní iframe. Virkar á https://bggj.shinyapps.io/sveitarfelog_maelabord/ 

líklega hægt að laga það svona : https://stackoverflow.com/questions/11032074/opening-a-specific-link-outside-the-iframe

Flott stöff samt!

**Comment by bgautijonsson** [comment]
Takk fyrir þetta. Búinn að uppfæra þetta mælaborð og fer í að uppfæra hin!
